-- MySQL Script generated by MySQL Workbench
-- Wed Jul 11 09:24:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `ncc` DEFAULT CHARACTER SET utf8 ;

use ncc;

CREATE TABLE IF NOT EXISTS `ncc`.`technology_info` (
  `tech_id` INT NOT NULL AUTO_INCREMENT,
  `technology` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tech_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ncc`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ncc`.`project` (
  `project_id` INT(11) NOT NULL AUTO_INCREMENT,
  `projectName` VARCHAR(45) NOT NULL,
  `customer` VARCHAR(45) NOT NULL,
  `PM` VARCHAR(45) NOT NULL,
  `tech_id` INT(11) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'running',
  `notes` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`),
   INDEX `pro_tech_key_idx` (`tech_id` ASC),
   CONSTRAINT `pro_tech_key`
    FOREIGN KEY (`tech_id`)
    REFERENCES `ncc`.`technology_info` (`tech_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;




CREATE TABLE IF NOT EXISTS `ncc`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ncc`.`log_time_sheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ncc`.`log_time_sheet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_id` INT(11) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `hours` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `user_id`, `project_id`),
  INDEX `uer_key_idx` (`user_id` ASC),
  INDEX `fk_log time sheet_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_log time sheet_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `ncc`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `log_user_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `ncc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ncc`.`relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ncc`.`relation` (
  `user_id` INT(11) NOT NULL,
  `project_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
  INDEX `proj_key_idx` (`project_id` ASC),
  CONSTRAINT `rela_proj_key`
    FOREIGN KEY (`project_id`)
    REFERENCES `ncc`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `rela_user_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `ncc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ncc`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ncc`.`user_info` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `job` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `user_key_idx` (`user_id` ASC),
  CONSTRAINT `user_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `ncc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
